#!/usr/bin/env python
"""Stream the Hanuman Chalisa illustrated paintings into the mastery module.

Maps each verse (doha 1/2, chaupai 1-40) to its painting in the
"Hanuman Chalisa - Illustrated" graphic novel, resizes to a phone-friendly JPEG,
uploads to a PUBLIC Supabase Storage bucket (dharma-art/chalisa/...), and writes
src/data/chalisaArt.ts mapping verseId -> public URL. App stays light (streamed).
"""
from __future__ import annotations
import os, re, json, subprocess, tempfile
from pathlib import Path
import requests
from dotenv import load_dotenv

AGENTIC = Path('/Users/kashyap/projects/Agentic-dharmaweave')
DHARMA = Path('/Users/kashyap/projects/dharma')
SRC = Path('/Users/kashyap/Library/CloudStorage/GoogleDrive-kashyap@tara-ventures.com/'
           'Shared drives/DharmaWeave/Creative & Content/Graphic Novels/'
           'The Hanuman Chalisa - Illustrated/Production Archive/Full Book')
ART_VERSION = 'v2'  # cache-bust query so devices fetch the clean re-uploads
load_dotenv(AGENTIC / '.env', override=True)
SUPA = os.environ['SUPABASE_URL']; SKEY = os.environ['SUPABASE_SERVICE_KEY']
BUCKET = 'dharma-art'
H = {'apikey': SKEY, 'Authorization': f'Bearer {SKEY}'}


def ensure_bucket():
    ids = [b.get('id') for b in requests.get(f'{SUPA}/storage/v1/bucket', headers=H, timeout=30).json()]
    if BUCKET not in ids:
        r = requests.post(f'{SUPA}/storage/v1/bucket', headers={**H, 'Content-Type': 'application/json'},
                          json={'id': BUCKET, 'name': BUCKET, 'public': True}, timeout=30)
        print('create bucket:', r.status_code, r.text[:100])
    else:
        print(f'bucket {BUCKET} exists')


def build_source_map() -> dict[str, Path]:
    """verseId -> clean single-painting path in Full Book (cNN.png, doha1/doha2.png)."""
    m: dict[str, Path] = {}
    d1 = SRC / 'doha1.png';  d2 = SRC / 'doha2.png'
    if d1.exists(): m['chalisa_doha_1'] = d1
    if d2.exists(): m['chalisa_doha_2'] = d2
    for n in range(1, 41):
        f = SRC / f'c{n:02d}.png'
        if f.exists():
            m[f'chalisa_chaupai_{n}'] = f
    return m


def resize_jpeg(src: Path, dst: Path) -> bool:
    # cp first to force Google Drive to materialize the file, then convert.
    tmp = Path(tempfile.gettempdir()) / ('raw_' + src.name)
    try:
        subprocess.run(['cp', str(src), str(tmp)], check=True)
        r = subprocess.run(['sips', '-s', 'format', 'jpeg', '-Z', '1400', str(tmp), '--out', str(dst)],
                           capture_output=True)
        tmp.unlink(missing_ok=True)
        return dst.exists() and dst.stat().st_size > 0
    except Exception as e:
        print('   resize err', e); return False


def upload(path: str, data: bytes) -> bool:
    r = requests.post(f'{SUPA}/storage/v1/object/{BUCKET}/{path}',
                      headers={**H, 'Content-Type': 'image/jpeg', 'x-upsert': 'true'},
                      data=data, timeout=120)
    return r.status_code in (200, 201)


def main():
    ensure_bucket()
    smap = build_source_map()
    verses = ['chalisa_doha_1', 'chalisa_doha_2'] + [f'chalisa_chaupai_{i}' for i in range(1, 41)]
    art: dict[str, str] = {}
    tmpd = Path(tempfile.gettempdir())
    for vid in verses:
        src = smap.get(vid)
        if not src:
            print(f'  {vid}: NO SOURCE'); continue
        dst = tmpd / f'{vid}.jpg'
        if not resize_jpeg(src, dst):
            print(f'  {vid}: resize FAILED ({src.name})'); continue
        ok = upload(f'chalisa/{vid}.jpg', dst.read_bytes())
        kb = dst.stat().st_size // 1024
        print(f'  {vid}: {kb}KB <- {src.name} upload={"ok" if ok else "FAIL"}')
        if ok:
            art[vid] = f'{SUPA}/storage/v1/object/public/{BUCKET}/chalisa/{vid}.jpg?{ART_VERSION}'
        dst.unlink(missing_ok=True)

    lines = ["// AUTO-GENERATED by scripts/gen_chalisa_art.py — do not edit by hand.",
             "// Per-verse Hanuman Chalisa paintings, streamed from Supabase Storage.",
             "export const CHALISA_ART: Record<string, string> = {"]
    for k, v in art.items():
        lines.append(f"  {json.dumps(k)}: {json.dumps(v)},")
    lines.append("};")
    (DHARMA / 'src' / 'data' / 'chalisaArt.ts').write_text('\n'.join(lines) + '\n')
    print(f'\nWrote {len(art)} paintings + src/data/chalisaArt.ts')


if __name__ == '__main__':
    main()
