#!/usr/bin/env python
"""Generate the Bhagavad Gita audio learning pack.

Pulls a curated set of iconic Gita shlokas (Devanagari + Hindi meaning) from the
DharmaWeave Postgres `wisdom` table, narrates each with the ElevenLabs **Kuber**
voice (eleven_v3), saves MP3s into the Dharma app, and writes a typed manifest
(src/data/gitaShlokas.ts) with static require() paths for React Native.

Run with the Agentic-dharmaweave venv:
  /Users/kashyap/projects/Agentic-dharmaweave/.venv/bin/python scripts/gen_gita_audio.py
"""
import os, re, json, time
from pathlib import Path
import psycopg2, requests
from dotenv import load_dotenv

AGENTIC = Path('/Users/kashyap/projects/Agentic-dharmaweave')
DHARMA = Path('/Users/kashyap/projects/dharma')
load_dotenv(AGENTIC / '.env', override=True)

KUBER = 'sZk20flPPGUa0sDxsZ8t'  # ElevenLabs "Kuber" — epic/Puranic Hindi narrator (canon)
MODEL = 'eleven_v3'
EL_KEY = os.environ['ELEVENLABS_API_KEY']

AUDIO_DIR = DHARMA / 'assets' / 'audio' / 'gita'
AUDIO_DIR.mkdir(parents=True, exist_ok=True)

# Curated, pedagogically ordered — the verses people actually want to learn.
ORDER = [
    'Chapter 2, Verse 13', 'Chapter 2, Verse 22', 'Chapter 2, Verse 47',
    'Chapter 2, Verse 48', 'Chapter 2, Verse 62', 'Chapter 2, Verse 63',
    'Chapter 4, Verse 7', 'Chapter 4, Verse 34', 'Chapter 6, Verse 6',
    'Chapter 6, Verse 19', 'Chapter 8, Verse 7', 'Chapter 18, Verse 66',
]

DEV_DIGITS = str.maketrans('0123456789', '०१२३४५६७८९')


def dev_num(n: int) -> str:
    return str(n).translate(DEV_DIGITS)


def fetch():
    conn = psycopg2.connect(os.environ['SUPABASE_DB_URL'])
    cur = conn.cursor()
    cur.execute(
        """select source_location, original_script, transliteration, translation_en, translation_hi
           from wisdom
           where source_location = ANY(%s)
             and (source_text ilike '%%gita%%' or source_text ilike '%%bhagavad%%')""",
        (ORDER,),
    )
    rows = {r[0]: r for r in cur.fetchall()}
    cur.close(); conn.close()
    return rows


def narrate(api_text: str, out: Path) -> bool:
    r = requests.post(
        f'https://api.elevenlabs.io/v1/text-to-speech/{KUBER}',
        headers={'xi-api-key': EL_KEY, 'Content-Type': 'application/json'},
        json={'text': api_text, 'model_id': MODEL,
              'voice_settings': {'stability': 0.6, 'similarity_boost': 0.8, 'style': 0.4}},
        timeout=120,
    )
    if r.status_code != 200:
        print(f'    EL error {r.status_code}: {r.text[:160]}')
        return False
    out.write_bytes(r.content)
    return True


def main():
    rows = fetch()
    manifest = []
    for loc in ORDER:
        if loc not in rows:
            print(f'  skip (not found): {loc}')
            continue
        _, script, translit, en, hi = rows[loc]
        m = re.match(r'Chapter (\d+), Verse (\d+)', loc)
        ch, v = int(m.group(1)), int(m.group(2))
        slug = f'gita_{ch}_{v}'
        title_hi = f'अध्याय {dev_num(ch)}, श्लोक {dev_num(v)}'

        # Kuber narration: announce, recite the shloka, then give the meaning — all Devanagari.
        shloka = (script or '').replace('\n', ' ').strip()
        meaning = (hi or '').strip()
        api_text = f'{title_hi}। {shloka} ।। इसका भाव है। {meaning}'

        out = AUDIO_DIR / f'{slug}.mp3'
        print(f'  {slug}  ({len(api_text)} chars) ...', end=' ')
        if narrate(api_text, out):
            print(f'ok ({out.stat().st_size // 1024} KB)')
        else:
            print('FAILED'); continue

        manifest.append({
            'id': slug, 'chapter': ch, 'verse': v,
            'titleHi': title_hi, 'titleEn': f'Chapter {ch}, Verse {v}',
            'sanskrit': shloka, 'transliteration': (translit or '').strip(),
            'meaningHi': meaning, 'meaningEn': (en or '').strip(),
            'audioFile': f'{slug}.mp3',
        })
        time.sleep(0.4)

    # Emit a typed manifest with static require() paths (RN requires literals).
    ts = ["// AUTO-GENERATED by scripts/gen_gita_audio.py — do not edit by hand.",
          "// Bhagavad Gita audio learning pack, narrated by Kuber (ElevenLabs).",
          "export interface GitaShloka {",
          "  id: string; chapter: number; verse: number;",
          "  titleHi: string; titleEn: string;",
          "  sanskrit: string; transliteration: string;",
          "  meaningHi: string; meaningEn: string; audio: any;",
          "}",
          "",
          "export const GITA_SHLOKAS: GitaShloka[] = ["]
    for e in manifest:
        ts.append("  {")
        ts.append(f"    id: {json.dumps(e['id'])}, chapter: {e['chapter']}, verse: {e['verse']},")
        ts.append(f"    titleHi: {json.dumps(e['titleHi'], ensure_ascii=False)}, titleEn: {json.dumps(e['titleEn'])},")
        ts.append(f"    sanskrit: {json.dumps(e['sanskrit'], ensure_ascii=False)},")
        ts.append(f"    transliteration: {json.dumps(e['transliteration'], ensure_ascii=False)},")
        ts.append(f"    meaningHi: {json.dumps(e['meaningHi'], ensure_ascii=False)},")
        ts.append(f"    meaningEn: {json.dumps(e['meaningEn'], ensure_ascii=False)},")
        ts.append(f"    audio: require('../../assets/audio/gita/{e['audioFile']}'),")
        ts.append("  },")
    ts.append("];")
    (DHARMA / 'src' / 'data' / 'gitaShlokas.ts').write_text('\n'.join(ts) + '\n')
    print(f'\nWrote {len(manifest)} tracks + src/data/gitaShlokas.ts')


if __name__ == '__main__':
    main()
