#!/usr/bin/env python
"""Generate the Hanuman Chalisa audio pack — STREAMED, not bundled.

Pulls all 43 Chalisa verses (Devanagari + Hindi meaning) from Postgres, narrates
each with Kuber (ElevenLabs), uploads the MP3s to a PUBLIC Supabase Storage bucket
(`dharma-audio/chalisa/...`), and writes a manifest (src/data/chalisaAudio.ts) of
PUBLIC URLs. The app streams + caches these on demand, so the binary stays light
and we can add packs without an App Store update.

Run: /Users/kashyap/projects/Agentic-dharmaweave/.venv/bin/python scripts/gen_chalisa_audio.py
"""
from __future__ import annotations
import json, os, re, time
from pathlib import Path
import psycopg2, requests
from dotenv import load_dotenv

AGENTIC = Path('/Users/kashyap/projects/Agentic-dharmaweave')
DHARMA = Path('/Users/kashyap/projects/dharma')
load_dotenv(AGENTIC / '.env', override=True)

SUPA = os.environ['SUPABASE_URL']
SKEY = os.environ['SUPABASE_SERVICE_KEY']
ELK = os.environ['ELEVENLABS_API_KEY']
KUBER = 'sZk20flPPGUa0sDxsZ8t'
MODEL = 'eleven_v3'
BUCKET = 'dharma-audio'

DEV = str.maketrans('0123456789', '०१२३४५६७८९')
H = {'apikey': SKEY, 'Authorization': f'Bearer {SKEY}'}


def ensure_bucket():
    r = requests.get(f'{SUPA}/storage/v1/bucket', headers=H, timeout=30)
    ids = [b.get('id') for b in r.json()] if r.status_code == 200 else []
    if BUCKET in ids:
        print(f'bucket {BUCKET} exists'); return
    r = requests.post(f'{SUPA}/storage/v1/bucket', headers={**H, 'Content-Type': 'application/json'},
                      json={'id': BUCKET, 'name': BUCKET, 'public': True}, timeout=30)
    print(f'create bucket {BUCKET}: {r.status_code} {r.text[:120]}')


def fetch():
    conn = psycopg2.connect(os.environ['SUPABASE_DB_URL']); cur = conn.cursor()
    cur.execute("""select source_location, original_script, transliteration, translation_en, translation_hi
                   from wisdom where source_text ilike '%hanuman chalisa%' or source_text ilike '%chalisa%'""")
    rows = cur.fetchall(); cur.close(); conn.close()

    def sortkey(r):
        loc = r[0] or ''
        m = re.search(r'(Doha|Chaupai)\s*(\d+)', loc, re.I)
        if not m:
            return (3, 0)
        kind, n = m.group(1).lower(), int(m.group(2))
        if kind == 'doha' and n <= 2:
            return (0, n)        # opening dohas
        if kind == 'chaupai':
            return (1, n)        # the 40 chaupai
        return (2, n)            # closing doha
    return sorted(rows, key=sortkey)


def narrate(text: str) -> bytes | None:
    r = requests.post(f'https://api.elevenlabs.io/v1/text-to-speech/{KUBER}',
                      headers={'xi-api-key': ELK, 'Content-Type': 'application/json'},
                      json={'text': text, 'model_id': MODEL,
                            'voice_settings': {'stability': 0.6, 'similarity_boost': 0.8, 'style': 0.4}},
                      timeout=120)
    if r.status_code != 200:
        print(f'    EL {r.status_code}: {r.text[:120]}'); return None
    return r.content


def upload(path: str, data: bytes) -> bool:
    r = requests.post(f'{SUPA}/storage/v1/object/{BUCKET}/{path}',
                      headers={**H, 'Content-Type': 'audio/mpeg', 'x-upsert': 'true'},
                      data=data, timeout=120)
    if r.status_code not in (200, 201):
        print(f'    upload {r.status_code}: {r.text[:120]}'); return False
    return True


def main():
    ensure_bucket()
    rows = fetch()
    print(f'{len(rows)} Chalisa verses')
    manifest = []
    for i, (loc, script, translit, en, hi) in enumerate(rows):
        m = re.search(r'(Doha|Chaupai)\s*(\d+)', loc or '', re.I)
        kind = (m.group(1).lower() if m else 'verse')
        num = int(m.group(2)) if m else i + 1
        slug = f'{kind}_{num}'
        title_hi = ('दोहा ' if kind == 'doha' else 'चौपाई ') + str(num).translate(DEV)
        title_en = f'{kind.capitalize()} {num}'
        shloka = (script or '').replace('\n', ' ').strip()
        meaning = (hi or '').strip()
        api_text = f'{shloka} ।। भावार्थ। {meaning}'

        audio = narrate(api_text)
        if not audio:
            print(f'  {slug}: FAILED narrate'); continue
        ok = upload(f'chalisa/{slug}.mp3', audio)
        print(f'  {slug}: {len(audio)//1024}KB upload={"ok" if ok else "FAIL"}')
        if not ok:
            continue
        manifest.append({
            'id': f'chalisa_{slug}', 'order': i, 'titleHi': title_hi, 'titleEn': title_en,
            'sanskrit': shloka, 'transliteration': (translit or '').strip(),
            'meaningHi': meaning, 'meaningEn': (en or '').strip(),
            'audioUrl': f'{SUPA}/storage/v1/object/public/{BUCKET}/chalisa/{slug}.mp3',
        })
        time.sleep(0.3)

    ts = ["// AUTO-GENERATED by scripts/gen_chalisa_audio.py — do not edit by hand.",
          "// Hanuman Chalisa audio pack (Kuber). Audio STREAMS from Supabase Storage + caches on device.",
          "export interface ChalisaVerse {",
          "  id: string; order: number; titleHi: string; titleEn: string;",
          "  sanskrit: string; transliteration: string; meaningHi: string; meaningEn: string; audioUrl: string;",
          "}",
          "",
          f"export const CHALISA_VERSES: ChalisaVerse[] = ["]
    for e in manifest:
        ts.append("  {")
        ts.append(f"    id: {json.dumps(e['id'])}, order: {e['order']},")
        ts.append(f"    titleHi: {json.dumps(e['titleHi'], ensure_ascii=False)}, titleEn: {json.dumps(e['titleEn'])},")
        ts.append(f"    sanskrit: {json.dumps(e['sanskrit'], ensure_ascii=False)},")
        ts.append(f"    transliteration: {json.dumps(e['transliteration'], ensure_ascii=False)},")
        ts.append(f"    meaningHi: {json.dumps(e['meaningHi'], ensure_ascii=False)},")
        ts.append(f"    meaningEn: {json.dumps(e['meaningEn'], ensure_ascii=False)},")
        ts.append(f"    audioUrl: {json.dumps(e['audioUrl'])},")
        ts.append("  },")
    ts.append("];")
    (DHARMA / 'src' / 'data' / 'chalisaAudio.ts').write_text('\n'.join(ts) + '\n')
    print(f'\nWrote {len(manifest)} streamed tracks + src/data/chalisaAudio.ts')


if __name__ == '__main__':
    main()
