// AUTO-GENERATED by scripts/gen_gita_audio.py — do not edit by hand.
// Bhagavad Gita audio learning pack, narrated by Kuber (ElevenLabs).
export interface GitaShloka {
  id: string; chapter: number; verse: number;
  titleHi: string; titleEn: string;
  sanskrit: string; transliteration: string;
  meaningHi: string; meaningEn: string; audio: any;
}

export const GITA_SHLOKAS: GitaShloka[] = [
  {
    id: "gita_2_13", chapter: 2, verse: 13,
    titleHi: "अध्याय २, श्लोक १३", titleEn: "Chapter 2, Verse 13",
    sanskrit: "देहिनोऽस्मिन्यथा देहे कौमारं यौवनं जरा । तथा देहान्तरप्राप्तिर्धीरस्तत्र न मुह्यति ॥",
    transliteration: "dehino 'smin yathā dehe kaumāraṁ yauvanaṁ jarā / tathā dehāntara-prāptir dhīras tatra na muhyati",
    meaningHi: "जैसे इस शरीर में जीवात्मा बालपन, जवानी और बुढ़ापे से गुजरती है, वैसे ही मृत्यु के बाद वह दूसरे शरीर में चली जाती है। धीर मनुष्य इस विषय में मोह नहीं करते।",
    meaningEn: "As the embodied soul continuously passes, in this body, from boyhood to youth to old age, so the soul passes into another body at death; the wise are not bewildered by this.",
    audio: require('../../assets/audio/gita/gita_2_13.mp3'),
  },
  {
    id: "gita_2_22", chapter: 2, verse: 22,
    titleHi: "अध्याय २, श्लोक २२", titleEn: "Chapter 2, Verse 22",
    sanskrit: "वासांसि जीर्णानि यथा विहाय नवानि गृह्णाति नरोऽपराणि । तथा शरीराणि विहाय जीर्णान्यन्यानि संयाति नवानि देही ॥",
    transliteration: "vāsāṁsi jīrṇāni yathā vihāya navāni gṛhṇāti naro 'parāṇi / tathā śarīrāṇi vihāya jīrṇāny anyāni saṁyāti navāni dehī",
    meaningHi: "जैसे मनुष्य पुराने वस्त्रों को त्याग कर नए वस्त्र धारण करता है, वैसे ही जीवात्मा पुराने और व्यर्थ हो चुके शरीरों को त्याग कर नए शरीरों को प्राप्त करती है।",
    meaningEn: "As a person puts on new garments, giving up old ones, the embodied soul accepts new bodies, giving up the old and worn.",
    audio: require('../../assets/audio/gita/gita_2_22.mp3'),
  },
  {
    id: "gita_2_47", chapter: 2, verse: 47,
    titleHi: "अध्याय २, श्लोक ४७", titleEn: "Chapter 2, Verse 47",
    sanskrit: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन। मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥",
    transliteration: "karmaṇyevādhikāraste mā phaleṣu kadācana | mā karmaphalaheturbhūrmā te saṅgo'stvakarmani ||",
    meaningHi: "तुम्हें केवल अपना निर्धारित कर्म करने का अधिकार है, लेकिन कर्म के फलों पर तुम्हारा कोई अधिकार नहीं है। तुम स्वयं को अपने कर्मों के फल का कारण मत मानो, और न ही काम न करने (अकर्मण्यता) के प्रति आसक्त हो।",
    meaningEn: "You have a right to perform your prescribed duty, but you are not entitled to the fruits of action. Never consider yourself the cause of the results of your activities, and never be attached to not doing your duty.",
    audio: require('../../assets/audio/gita/gita_2_47.mp3'),
  },
  {
    id: "gita_2_48", chapter: 2, verse: 48,
    titleHi: "अध्याय २, श्लोक ४८", titleEn: "Chapter 2, Verse 48",
    sanskrit: "योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय । सिद्ध्यसिद्ध्योः समो भूत्वा समत्वं योग उच्यते ॥",
    transliteration: "yoga-sthaḥ kuru karmāṇi saṅgaṁ tyaktvā dhanañjaya / siddhy-asiddhyoḥ samo bhūtvā samatvaṁ yoga ucyate",
    meaningHi: "हे धनंजय! योग में स्थित होकर और आसक्ति को त्याग कर कर्म करो। सफलता और विफलता में समान भाव रखना ही योग कहलाता है।",
    meaningEn: "Established in yoga, O Dhananjaya, perform action, abandoning attachment, even-minded in success and failure. Yoga is called evenness of mind.",
    audio: require('../../assets/audio/gita/gita_2_48.mp3'),
  },
  {
    id: "gita_2_62", chapter: 2, verse: 62,
    titleHi: "अध्याय २, श्लोक ६२", titleEn: "Chapter 2, Verse 62",
    sanskrit: "ध्यायतो विषयान्पुंसः सङ्गस्तेषूपजायते । सङ्गात्सञ्जायते कामः कामात्क्रोधोऽभिजायते ॥",
    transliteration: "dhyāyato viṣayān puṁsaḥ saṅgas teṣūpajāyate / saṅgāt sañjāyate kāmaḥ kāmāt krodho 'bhijāyate",
    meaningHi: "विषयों (इन्द्रिय सुखों) का चिंतन करने से मनुष्य की उनमें आसक्ति हो जाती है। आसक्ति से इच्छा (कामना) पैदा होती है, और इच्छा में बाधा पड़ने से क्रोध उत्पन्न होता है।",
    meaningEn: "Brooding on objects of sense, a man develops attachment to them; from attachment springs desire; from desire arises anger.",
    audio: require('../../assets/audio/gita/gita_2_62.mp3'),
  },
  {
    id: "gita_2_63", chapter: 2, verse: 63,
    titleHi: "अध्याय २, श्लोक ६३", titleEn: "Chapter 2, Verse 63",
    sanskrit: "क्रोधाद्भवति सम्मोहः सम्मोहात्स्मृतिविभ्रमः । स्मृतिभ्रंशाद्बुद्धिनाशो बुद्धिनाशात्प्रणश्यति ॥",
    transliteration: "krodhād bhavati sammohaḥ sammohāt smṛti-vibhramaḥ / smṛti-bhraṁśād buddhi-nāśo buddhi-nāśāt praṇaśyati",
    meaningHi: "क्रोध से मूढ़ता (भ्रम) उत्पन्न होती है, मूढ़ता से स्मृति भ्रमित हो जाती है। स्मृति के भ्रमित होने से बुद्धि नष्ट हो जाती है, और बुद्धि के नाश होने से मनुष्य का पतन हो जाता है।",
    meaningEn: "From anger comes delusion; from delusion, confusion of memory; from confusion of memory, loss of reason; from loss of reason, one perishes.",
    audio: require('../../assets/audio/gita/gita_2_63.mp3'),
  },
  {
    id: "gita_4_7", chapter: 4, verse: 7,
    titleHi: "अध्याय ४, श्लोक ७", titleEn: "Chapter 4, Verse 7",
    sanskrit: "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत। अभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम्॥",
    transliteration: "yadā yadā hi dharmasya glānirbhavati bhārata | abhyutthānamadharamasya tadātmānaṁ sṛjāmyaham ||",
    meaningHi: "हे भरतवंशी, जब-जब धर्म की हानि और अधर्म का उत्थान होता है, तब-तब मैं स्वयं को प्रकट करता हूँ (अवतार लेता हूँ)।",
    meaningEn: "Whenever and wherever there is a decline in religious practice, O descendant of Bharata, and a predominant rise of irreligion—at that time I descend Myself.",
    audio: require('../../assets/audio/gita/gita_4_7.mp3'),
  },
  {
    id: "gita_4_34", chapter: 4, verse: 34,
    titleHi: "अध्याय ४, श्लोक ३४", titleEn: "Chapter 4, Verse 34",
    sanskrit: "तद्विद्धि प्रणिपातेन परिप्रश्नेन सेवया । उपदेक्ष्यन्ति ते ज्ञानं ज्ञानिनस्तत्त्वदर्शिनः ॥",
    transliteration: "tad viddhi praṇipātena paripraśnena sevayā / upadekṣyanti te jñānaṁ jñāninas tattva-darśinaḥ",
    meaningHi: "उस ज्ञान को तुम गुरु के पास जाकर समझो। उन्हें साष्टांग प्रणाम करने से, विनम्रतापूर्वक प्रश्न पूछने से और उनकी सेवा करने से, वे तत्त्वदर्शी ज्ञानी तुम्हें उस ज्ञान का उपदेश देंगे।",
    meaningEn: "Know that by surrender, by questioning, by service: the seers of truth, who have realized knowledge, will instruct you.",
    audio: require('../../assets/audio/gita/gita_4_34.mp3'),
  },
  {
    id: "gita_6_6", chapter: 6, verse: 6,
    titleHi: "अध्याय ६, श्लोक ६", titleEn: "Chapter 6, Verse 6",
    sanskrit: "बन्धुरात्मात्मनस्तस्य येनात्मैवात्मना जितः। अनात्मनस्तु शत्रुत्वे वर्तेतात्मैव शत्रुवत्।।",
    transliteration: "bandhur ātmātmanas tasya yenātmaivātmanā jitaḥ, anātmanas tu śatrutve vartetātmaiva śatru-vat",
    meaningHi: "जिसने अपने मन और इन्द्रियों को जीत लिया है, उसके लिए उसका मन ही उसका सबसे अच्छा मित्र है। लेकिन जो अपने मन को नहीं जीत पाया है, उसके लिए उसका अपना मन ही शत्रु के समान काम करता है।",
    meaningEn: "For him who has conquered the mind, the mind is the best of friends; but for one who has failed to do so, his mind will remain the greatest enemy.",
    audio: require('../../assets/audio/gita/gita_6_6.mp3'),
  },
  {
    id: "gita_6_19", chapter: 6, verse: 19,
    titleHi: "अध्याय ६, श्लोक १९", titleEn: "Chapter 6, Verse 19",
    sanskrit: "यथा दीपो निवातस्थो नेङ्गते सोपमा स्मृता। योगिनो यतचित्तस्य युञ्जतो योगमात्मनः॥",
    transliteration: "yathā dīpo nivāta-stho neṅgate sopamā smṛtā / yogino yata-cittasya yuñjato yogam ātmanaḥ",
    meaningHi: "जिस प्रकार वायुरहित स्थान में रखा हुआ दीपक नहीं हिलता, उसी प्रकार आत्म-ध्यान में लगे हुए और संयमित चित्त वाले योगी की उपमा दी जाती है।",
    meaningEn: "As a lamp in a windless place does not flicker — to such is compared the yogi of controlled mind, practicing yoga of the Self.",
    audio: require('../../assets/audio/gita/gita_6_19.mp3'),
  },
  {
    id: "gita_8_7", chapter: 8, verse: 7,
    titleHi: "अध्याय ८, श्लोक ७", titleEn: "Chapter 8, Verse 7",
    sanskrit: "तस्मात्सर्वेषु कालेषु मामनुस्मर युध्य च । मय्यर्पितमनोबुद्धिर्मामेवैष्यस्यसंशयः ॥",
    transliteration: "tasmāt sarveṣu kāleṣu mām anusmara yudhya ca, mayy arpita-mano-buddhir mām evaiṣyasy asaṁśayaḥ",
    meaningHi: "इसलिए हे अर्जुन, तुम हर समय मेरा ही स्मरण करो और अपना युद्ध करने का कर्तव्य भी निभाओ। अपने मन और बुद्धि को मुझमें अर्पित करके, तुम निस्संदेह मुझे ही प्राप्त करोगे।",
    meaningEn: "Therefore, Arjuna, you should always think of Me in the form of Krishna and at the same time carry out your prescribed duty of fighting. With your activities dedicated to Me and your mind and intelligence fixed on Me, you will attain Me without doubt.",
    audio: require('../../assets/audio/gita/gita_8_7.mp3'),
  },
  {
    id: "gita_18_66", chapter: 18, verse: 66,
    titleHi: "अध्याय १८, श्लोक ६६", titleEn: "Chapter 18, Verse 66",
    sanskrit: "सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज । अहं त्वां सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः ॥",
    transliteration: "sarvadharmānparityajya māmekaṃ śaraṇaṃ vraja |\nahaṃ tvāṃ sarvapāpebhyo mokṣayiṣyāmi mā śucaḥ ||",
    meaningHi: "सभी प्रकार के धर्मों का परित्याग कर केवल मेरी शरण में आओ। मैं तुम्हें समस्त पापों से मुक्त कर दूँगा। डरो मत।",
    meaningEn: "Abandon all varieties of religion and just surrender unto Me. I shall deliver you from all sinful reactions. Do not fear.",
    audio: require('../../assets/audio/gita/gita_18_66.mp3'),
  },
];
